---
title: "L10 Joins & Missingness"
subtitle: "Data Science 1 with R (STAT 301-1)"
author: "YOUR NAME"

format:
  html:
    toc: true
    embed-resources: true
    code-fold: show
    link-external-newwindow: true

execute:
  warning: false
  
from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[https://your-github-repo-url](https://your-github-repo-url)

:::

## Overview

The goal of this lab is to learn and understand the concepts of **relational data**. It is extremely rare that data analyses involve one all-encompassing dataset; we usually want to combine information from multiple data tables/sources to answer interesting questions. The collection of data tables/sources is called **relational data** because it is the relations connecting the datasets together that are important.

- See [two-table verbs in `dplyr`](https://dplyr.tidyverse.org/articles/two-table.html) for more information concerning relational data. 
- [Relational Database Wikipedia Page](https://en.wikipedia.org/wiki/Relational_database)

## Load packages

You should always begin by loading all necessary packages towards the beginning of your document.

```{r}
#| label: load-pkgs
#| code-fold: false

# Loading package(s)

```

## Datasets 

All datasets are found within R packages, which students should be able to identify and download as needed.

## Exercises

### Exercise 1 

Describe in your own words what the functions `left_join`, `right_join`, `inner_join`, and `full_join` accomplish.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Exercise 2

A relationship between `nycflights13::weather` and `nycflights13::airports` is possible. Describe the relationship using appropriate primary/foreign key vocabulary for relational data.


::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Exercise 3

What weather conditions make it more likely to see a departure delay?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::


### Exercise 4

What does `anti_join(flights, airports, by = c("dest" = "faa"))` tell you? 

What does `anti_join(airports, flights, by = c("faa" = "dest"))` tell you?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::


### Exercise 5

Combine `fueleconomy::vehicles` and `fueleconomy::common` to find the records for only the most common models.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::


## Case Study 1

### Exploration 1

Use `rankings_2021` and `rankings_2022` to answer the following questions^[This data was obtained from [Times Higher Education](https://www.timeshighereducation.com/rankings/united-states/2022#!/length/-1/sort_by/rank/sort_order/asc/cols/scores) and [College Scorecard](https://collegescorecard.ed.gov/data)]:

a) What types of explicit missingness exists in `rankings_2021` and `rankings_2022`, if any?
b) What types of implicit missingness exists in `rankings_2021` and `rankings_2022`, if any?
c) What is the "key" and is it a primary, compound primary, foreign, or surrogate key?


::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Exploration 2

Combine `rankings_2021` and `rankings_2022` to answer the following questions:

a) Which colleges had tuition increase the most from 2021 to 2022?
b) Only considering colleges ranked in the top 400, which college increased the most in ranking from 2021 to 2022?
c) Which colleges were ranked in 2021 but not ranked in 2022? which colleges were ranked in 2022 but not ranked in 2021?


::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::


## Case Study 2

Add a new variable called `year` which has the value of `2021` for each observation of `rankings_2021` and the value of `2022` for each observation of `rankings_2022`. Then use `bind_rows()` to combine `rankings_2021` and `rankings_2022`.  

When might you use `bind_rows` or `bind_cols` instead of a `join`?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::



